"""add_knowledge_files

Revision ID: 87f192e74df0
Revises: b81aa7632812
Create Date: 2026-05-23 21:36:01.041454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f192e74df0'
down_revision: Union[str, Sequence[str], None] = 'b81aa7632812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='文件唯一标识'),
    sa.Column('knowledge_base_id', sa.UUID(as_uuid=False), nullable=False, comment='所属知识库 ID'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='上传者 ID'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='存储文件名'),
    sa.Column('original_filename', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment='文件存储路径'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型: pdf/docx/md/txt/code/image'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态: processing/completed/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('chunks_count', sa.Integer(), nullable=False, comment='生成的知识片段数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_files_knowledge_base_id'), 'knowledge_files', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_user_id'), 'knowledge_files', ['user_id'], unique=False)
    op.add_column('knowledge_items', sa.Column('file_id', sa.UUID(as_uuid=False), nullable=True, comment='来源文件 ID'))
    op.create_index(op.f('ix_knowledge_items_file_id'), 'knowledge_items', ['file_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_items', 'knowledge_files', ['file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_items_file_id'), table_name='knowledge_items')
    op.drop_column('knowledge_items', 'file_id')
    op.drop_index(op.f('ix_knowledge_files_user_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_knowledge_base_id'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    # ### end Alembic commands ###
