"""初始表结构

Revision ID: b81aa7632812
Revises: 
Create Date: 2026-05-23 18:57:56.125372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b81aa7632812'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Agent 唯一标识'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='Agent 描述'),
    sa.Column('knowledge_ids', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=False, comment='关联的知识条目 ID 列表'),
    sa.Column('prompt_template', sa.Text(), nullable=True, comment='系统提示词模板，为空则自动生成'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='用户唯一标识'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名（唯一登录标识）'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt 哈希后的密码'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='用户角色: super_admin / user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='对话唯一标识'),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False, comment='关联 Agent ID'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='用户 ID'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='对话标题（默认取自第一条用户消息）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='知识库唯一标识'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='所属用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='条目唯一标识'),
    sa.Column('knowledge_base_id', sa.UUID(as_uuid=False), nullable=False, comment='所属知识库 ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='条目标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='条目内容（Markdown）'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='类型：document / qa / code / other'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：available / unavailable'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment='标签列表'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='来源：manual / import / agent_extract'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True, comment='BGE-M3 向量 (1024 维)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='消息唯一标识'),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False, comment='所属对话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user / assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='引用来源列表 [{index, content, knowledge_title, score}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('agents')
    # ### end Alembic commands ###
